######################################################################################
#                                                                                    #
#   Project Workflow Scripts                                                         #
#   Copyright (C) 2019  Nicholas Passon                                              #
#   Documentation: Coming Soon                                                       #
#                                                                                    #
#   This program is free software: you can redistribute it and/or modify             #
#   it under the terms of the GNU Affero General Public License as published         #
#   by the Free Software Foundation, either version 3 of the License, or             #
#   (at your option) any later version.                                              #
#                                                                                    #
#   This program is distributed in the hope that it will be useful,                  #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of                   #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    #
#   GNU Affero General Public License for more details.                              #
#                                                                                    #
#   You should have received a copy of the GNU Affero General Public License         #
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.            #
#                                                                                    #
######################################################################################

image: node:8

# define variables
variables:
  PROJECT_ID: ""
  DEMO_SERVER: ""
  DEMO_USE_SFTP: ""
  DEMO_FTP_USER: ""
  DEMO_FTP_PASS: ""
  DEMO_SFTP_USER: ""
  DEMO_CURRENT_STATUS: ""
  DEMO_TRANSITION_ID: ""
  LIVE_USE_SFTP: ""
  LIVE_FTP_USER: ""
  LIVE_FTP_PASS: ""
  LIVE_SFTP_USER: ""
  LIVE_SERVER: ""
  LIVE_CURRENT_STATUS: ""
  LIVE_TRANSITION_ID: ""
  JIRA_URL: ""
  JIRA_USER: ""
  JIRA_PASS: ""

# run validation checks and SSH setup
before_script:
  - sudo chmod -R 777 ./scripts
  - . ./scripts/before_script.sh

## If everything goes well, the execution is as follows:
## 1. build
##    Compile files as needed. This step can be modified
##    and added to as needed by the user.
##
## 2. deploydemo/deploylive, depending on updated branch
##    Upload the /build folder to the respective server
##
## 3. jiratodemo/jiratolive
##    Move all tickets currently in "to be uploaded" state
##    to the respective "Live" or "Live on demo" state

stages:
##  build
  - build
##  deploydemo, deploylive
  - deploy
##  jiratodemo, jiratolive
  - transition

##
## Deploy to demo if branch is 'dev'
##
deploydemo:
  stage: deploy
  only:
##    Only deploy to demo if "dev" branch was updated
##    TODO: Custom branches
    - dev
  dependencies:
##    depends on both PostCSS and UglifyJS to complete
##    don't want to upload broken files
    - postcss
    - uglifyjs
  script:
    - . ./scripts/deploydemo.sh
  environment:
##  define environments
##  TODO: Custom enviroments
    name: demo
    url: http://localhost/

##
## Deploy to live if branch is 'master'
##
deploylive:
  stage: deploy
  only:
##    Only deploy to demo if "master" branch was updated
##    TODO: Custom branches
    - master
  dependencies:
##    depends on both PostCSS and UglifyJS to complete
##    don't want to upload broken files
    - postcss
    - uglifyjs
  script:
    - . ./scripts/deploylive.sh
  environment:
##  define environments
##  TODO: Custom enviroments
    name: live
    url: http://localhost/

##
## Move JIRA ticket to 'Live on Demo' if branch is 'dev' and upload succeeded
##
jiratodemo:
  stage: transition
  only:
##    Only deploy to demo if "dev" branch was updated
##    TODO: Custom branches
    - dev
  dependencies:
##    only run if deploy has succeeded
    - deploydemo
  script:
    - . ./scripts/jiratodemo.sh

##
## Move JIRA ticket to 'Live on Demo' if branch is 'dev' and upload succeeded
##
jiratolive:
  stage: transition
  only:
##    Only deploy to demo if "master" branch was updated
##    TODO: Custom branches
    - master
  dependencies:
##    only run if deploy has succeeded
    - deploylive
  script:
    - . ./scripts/jiratolive.sh
