######################################################################################
#                                                                                    #
#   Project Workflow Scripts                                                         #
#   Copyright (C) 2019  Nicholas Passon                                              #
#   Documentation: Coming Soon                                                       #
#                                                                                    #
#   This program is free software: you can redistribute it and/or modify             #
#   it under the terms of the GNU Affero General Public License as published         #
#   by the Free Software Foundation, either version 3 of the License, or             #
#   (at your option) any later version.                                              #
#                                                                                    #
#   This program is distributed in the hope that it will be useful,                  #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of                   #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    #
#   GNU Affero General Public License for more details.                              #
#                                                                                    #
#   You should have received a copy of the GNU Affero General Public License         #
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.            #
#                                                                                    #
######################################################################################

# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! #
# Do not change any identifiers in this file which  #
# are starting with a dot, e.g. .deploy_live        #
# ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! #

include:
  - project: 'my-group/my-project' # TODO: git repository of template file
    file: '.gitlab-ci.template.yml'

jira_demo:
  extends: .jira_demo
  only:
    - dev

jira_live:
  extends: .jira_live
  only:
    - master

deploy_demo:
  extends: .deploy_demo
  only:
    - master
  environment:
    name: 'Live-Server'
    url: 'http://example.com'

deploy_live:
  extends: .deploy_live
  only:
    - dev
  environment:
    name: 'Demo-Server'
    url: 'http://example.com'



##############################################
### INSERT YOUR CUSTOM BUILD STAGES BELOW! ###
##############################################

## This is an example step for the Gitlab CI build stage.
## You can modify everything here, except the 'stage: build' line.
## You can also dupliate this whole step, just remember to rename it.
build_stage_name:
  stage: build
  image: node:8
  script:
##    install PostCSS from NPM
    - npm i -g postcss-cli
##    install CSSNano to minify CSS
    - npm install cssnano
##    compile postcss
    - cat ./src/css/* | postcss --no-map > ./build/src/css/main.css
  artifacts:
    paths:
##      make sure we transfer the CSS file over to the deploy stage
      - build/src/css/main.css
    expire_in: 1 day
